[package]
name = "quote-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
serenity = "0.12"
poise = "0.6.1"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
dotenvy = "0.15"
