name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  # build-and-push:
  #   name: Build and Push Docker Image
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
      
  #     - name: Login to Docker Hub
  #       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

  #     - name: Build Docker image
  #       run: docker build -t ${{ secrets.DOCKER_USERNAME }}/quote-bot:latest .
      
  #     - name: Push image to Docker Hub
  #       run: docker push ${{ secrets.DOCKER_USERNAME }}/quote-bot:latest 
        
  deploy:
    name: Deploy on EC2
    # needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      
      - name: Copy files to EC2
        run: |
          rsync -avz --exclude 'target' --exclude '.git' -e "ssh -i ~/.ssh/id_rsa" ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/quote-bot

      - name: Deploy on EC2 using Docker Hub image
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            docker pull ${{ secrets.DOCKER_USERNAME }}/quote-bot:latest
            docker stop quote-bot || true
            docker rm quote-bot || true
            docker run -d \
              --restart unless-stopped \
              --name quote-bot \
              -v /home/${{ secrets.EC2_USER }}/quote-bot/.env:/app/.env \
              -v /home/${{ secrets.EC2_USER }}/quote-bot/quotes.db:/app/quotes.db \
              -v /home/${{ secrets.EC2_USER }}/quote-bot/user_map.json:/app/user_map.json \
              ${{ secrets.DOCKER_USERNAME }}/quote-bot:latest
          EOF